# Generated by Django 5.1.4 on 2025-01-27 15:43

from django.db import migrations
from apps.codificadores.fixtures import F001_datos_iniciales_codificadores


def load_data(apps, schema_editor):
    F001_datos_iniciales_codificadores.init_data(apps, schema_editor)


class Migration(migrations.Migration):
    dependencies = [
        ('codificadores', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(load_data)
    ]
