# Generated by Django 5.2.6 on 2025-10-01 16:30

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codificadores', '0002_cargar_datos_iniciales'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoHabilitacion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=100, unique=True, verbose_name='Tipo Habilitación')),
                ('activo', models.BooleanField(default=True, verbose_name='Active')),
            ],
            options={
                'db_table': 'cla_tipohabilitacion',
                'ordering': ['descripcion'],
            },
        ),
        migrations.AlterModelOptions(
            name='centrocosto',
            options={'ordering': ['clave', 'descripcion'], 'verbose_name': 'Cost center', 'verbose_name_plural': 'Centers of cost'},
        ),
        migrations.CreateModel(
            name='ProductoFlujoTipoHabilitacion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productoflujotipohabilitacion_producto', to='codificadores.productoflujo')),
                ('tipohabilitacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='productosflujo_tipohabilitacion', to='codificadores.tipohabilitacion')),
            ],
            options={
                'db_table': 'cla_productoflujotipohabilitacion',
            },
        ),
    ]
