# Generated by Django 5.2.6 on 2025-10-07 19:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codificadores', '0003_tipohabilitacion_alter_centrocosto_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clasificadorcargos',
            name='salario_calculado',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18, validators=[django.core.validators.MinValueValidator(0.0, message='El valor debe ser >= 0')], verbose_name='Salario Calculado'),
        ),
    ]
