# Generated by Django 5.2.6 on 2025-10-20 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codificadores', '0004_clasificadorcargos_salario_calculado'),
    ]

    operations = [
        migrations.AddField(
            model_name='departamento',
            name='es_almacen',
            field=models.BooleanField(default=False, verbose_name='Es Almacén'),
        ),
    ]
