# Generated by Django 5.2.4 on 2025-10-07 09:42

import apps.codificadores.models
import apps.costo.models
import django.core.validators
import django.db.models.deletion
import django.db.models.functions.datetime
import django.db.models.manager
import django_choices_field.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('codificadores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FichaCostoProducto',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fecha_creacion', models.DateTimeField(db_default=django.db.models.functions.datetime.Now(), verbose_name='Crate at')),
                ('fecha', models.DateField(verbose_name='Date')),
                ('cantidad', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0, message='The value must be greater than 0')])),
                ('tasa', models.DecimalField(db_comment='Tasa', decimal_places=6, default=0.0, max_digits=10, verbose_name='Tasa')),
                ('activa', models.BooleanField(default=False, verbose_name='Active')),
                ('confirmada', models.BooleanField(default=False, verbose_name='Confirmada')),
                ('tipoficha', django_choices_field.fields.IntegerChoicesField(choices=[(1, 'Torcido'), (2, 'Terminado')], choices_enum=apps.costo.models.TipoFichaCosto, verbose_name='Tipo Ficha')),
                ('medida', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ficha_medida', to='codificadores.medida', verbose_name='U.M')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='productoflujo_ficha', to='codificadores.productoflujo', verbose_name='Product')),
            ],
            options={
                'db_table': 'cos_fichacostoproducto',
                'ordering': ['fecha', 'producto', 'confirmada', '-activa'],
            },
        ),
        migrations.CreateModel(
            name='FichaCostoGrouped',
            fields=[
            ],
            options={
                'verbose_name': 'Ficha de Costo',
                'verbose_name_plural': 'Fichas de Costo',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('costo.fichacostoproducto',),
        ),
        migrations.CreateModel(
            name='FichaCostoProductoFilas',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('costo', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Costo')),
                ('fichacostoproducto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fichacostoproducto_ficha', to='costo.fichacostoproducto', verbose_name='Ficha de Costo')),
                ('fila', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fichacostoproducto_fila', to='codificadores.fichacostofilas')),
            ],
            options={
                'db_table': 'cos_fichacostoproductofila',
                'ordering': ['fila'],
            },
        ),
        migrations.CreateModel(
            name='FichaCostoProductoFilaDesgloseSalario',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('salario', models.DecimalField(db_comment='Salario', decimal_places=2, max_digits=10, verbose_name='Salario')),
                ('salario_calculado', models.DecimalField(db_comment='Salario Calculado', decimal_places=2, default=0.0, max_digits=18, verbose_name='Salario Calculado')),
                ('cantidad', models.IntegerField(default=0, verbose_name='Cantidad de Trabajadores')),
                ('nr_media', models.IntegerField(db_comment='Norma de Rendimiento Media para los trabajadores directos', default=0, verbose_name='Norma Rendimiento Media')),
                ('norma_tiempo', models.DecimalField(decimal_places=4, default=0, max_digits=10, verbose_name='Norma de tiempo (hrs)')),
                ('cargo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='filadesglose_cargo', to='codificadores.clasificadorcargos', verbose_name='Cargo')),
                ('fila', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='desglosesalario_fila', to='costo.fichacostoproductofilas', verbose_name='Fila')),
            ],
            options={
                'db_table': 'cos_fichacostoproductofiladesglosesalario',
                'ordering': ['fila', 'cargo'],
            },
        ),
        migrations.CreateModel(
            name='FichaCostoProductoFilaDesgloseMPMat',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('costo_base_norma', models.DecimalField(db_default=0.0, decimal_places=4, max_digits=10, verbose_name='Norma Costo Base')),
                ('costo_base_precio', models.DecimalField(db_default=0.0, decimal_places=6, max_digits=10, verbose_name='Precio Costo Base')),
                ('costo_base_importe', models.DecimalField(db_default=0.0, decimal_places=2, max_digits=10, verbose_name='Importe Costo Base')),
                ('costo_propuesto_norma', models.DecimalField(db_default=0.0, decimal_places=4, max_digits=10, verbose_name='Norma Costo Base')),
                ('costo_propuesto_precio', models.DecimalField(db_default=0.0, decimal_places=6, max_digits=10, verbose_name='Precio Costo Base')),
                ('costo_propuesto_importe', models.DecimalField(db_default=0.0, decimal_places=2, max_digits=10, verbose_name='Importe Costo Propuesto')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='filadesglose_producto', to='codificadores.productoflujo', verbose_name='Product')),
                ('fila', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='desglosempmat_fila', to='costo.fichacostoproductofilas', verbose_name='Fila')),
            ],
            options={
                'db_table': 'cos_fichacostoproductofiladesglosempmat',
                'ordering': ['fila', 'producto'],
            },
        ),
        migrations.CreateModel(
            name='FichaCostoProductoFilaCapas',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('costo_base_norma', models.DecimalField(db_default=0.0, decimal_places=4, max_digits=10, verbose_name='Norma Costo Base')),
                ('costo_base_precio', models.DecimalField(db_default=0.0, decimal_places=6, max_digits=10, verbose_name='Precio Costo Base')),
                ('costo_base_importe', models.DecimalField(db_default=0.0, decimal_places=2, max_digits=10, verbose_name='Importe Costo Base')),
                ('costo_propuesto_norma', models.DecimalField(db_default=0.0, decimal_places=4, max_digits=10, verbose_name='Norma Costo Base')),
                ('costo_propuesto_precio', models.DecimalField(db_default=0.0, decimal_places=6, max_digits=10, verbose_name='Precio Costo Base')),
                ('costo_propuesto_importe', models.DecimalField(db_default=0.0, decimal_places=2, max_digits=10, verbose_name='Importe Costo Propuesto')),
                ('fila', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='desglosecapas_fila', to='costo.fichacostoproductofilas', verbose_name='Fila')),
            ],
            options={
                'db_table': 'cos_fichacostoproductofilacapas',
                'ordering': ['fila'],
            },
        ),
        migrations.CreateModel(
            name='VarGlobalesCosto',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('anno', models.IntegerField(default=0, verbose_name='Año')),
                ('mes', models.IntegerField(default=0, verbose_name='Mes')),
                ('centrocosto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='varglobal_cc', to='codificadores.centrocosto', verbose_name='Centro Costo')),
                ('ueb', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='varglobal_ueb', to='codificadores.unidadcontable')),
            ],
            options={
                'verbose_name': 'Centro de Costo Variables Globales',
                'verbose_name_plural': 'Centros de Costo Variables Globales',
                'db_table': 'cos_varglobalescosto',
                'ordering': ['ueb__codigo', 'centrocosto__descripcion', '-anno', '-mes'],
            },
        ),
        migrations.CreateModel(
            name='VarGlobalesCostoDatos',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('destino', django_choices_field.fields.TextChoicesField(choices=[('C', 'Consumo Nacional'), ('E', 'Exportación')], choices_enum=apps.codificadores.models.Destino, max_length=1, verbose_name='Destination')),
                ('valor', models.DecimalField(db_default=0.0, decimal_places=2, max_digits=18, verbose_name='Valor')),
                ('varglobalescosto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='varglobaldatos_varglobalescosto', to='costo.varglobalescosto')),
                ('variable_global', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='varglobaldatos_variable', to='codificadores.costovarglobales', verbose_name='Variable')),
            ],
            options={
                'verbose_name': 'Valor de la Variable Global del Costo',
                'verbose_name_plural': 'Valor de las Variables Globales del Costo',
                'db_table': 'cos_varglobalescostodatos',
                'ordering': ['variable_global__descripcion', 'destino', 'variable_global__activa'],
            },
        ),
        migrations.CreateModel(
            name='FechaProcesamientoCosto',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('anno', models.IntegerField(default=0, verbose_name='Año')),
                ('mes', models.IntegerField(default=0, verbose_name='Mes')),
                ('inicial', models.BooleanField(default=False, verbose_name='Inicial')),
                ('ueb', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fechaprocesamientocosto_ueb', to='codificadores.unidadcontable')),
            ],
            options={
                'verbose_name': 'Fecha de Procesamiento del Costo',
                'verbose_name_plural': 'Fechas de Procesamiento del Costo',
                'db_table': 'cos_fechaprocesamientocosto',
                'ordering': ['ueb__codigo'],
                'indexes': [models.Index(fields=['ueb', 'mes', 'anno'], name='cos_fechapr_ueb_id_e87373_idx')],
                'constraints': [models.UniqueConstraint(fields=('mes', 'anno', 'ueb'), name='unique_fechaproceccosto')],
            },
            managers=[
                ('objects_cache', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddIndex(
            model_name='fichacostoproducto',
            index=models.Index(fields=['producto', 'activa'], name='cos_fichaco_product_9e1876_idx'),
        ),
        migrations.AddConstraint(
            model_name='fichacostoproductofilas',
            constraint=models.UniqueConstraint(fields=('fila', 'fichacostoproducto'), name='unique_fichacostoproductofila_fila_fichacostoproducto'),
        ),
        migrations.AddConstraint(
            model_name='fichacostoproductofiladesglosesalario',
            constraint=models.UniqueConstraint(fields=('fila', 'cargo'), name='unique_fichacostoproductofiladesglosesalario_fila_salario'),
        ),
        migrations.AddConstraint(
            model_name='fichacostoproductofiladesglosempmat',
            constraint=models.UniqueConstraint(fields=('fila', 'producto'), name='unique_fichacostoproductofiladesglosempmat_fila_producto'),
        ),
        migrations.AddIndex(
            model_name='varglobalescosto',
            index=models.Index(fields=['ueb', 'mes', 'anno', 'centrocosto'], name='cos_varglob_ueb_id_0406df_idx'),
        ),
        migrations.AddConstraint(
            model_name='varglobalescosto',
            constraint=models.UniqueConstraint(fields=('ueb', 'mes', 'anno', 'centrocosto'), name='unique_varglobalescosto'),
        ),
        migrations.AddIndex(
            model_name='varglobalescostodatos',
            index=models.Index(fields=['variable_global', 'destino'], name='cos_varglob_variabl_ab85ea_idx'),
        ),
        migrations.AddConstraint(
            model_name='varglobalescostodatos',
            constraint=models.UniqueConstraint(fields=('varglobalescosto', 'variable_global', 'destino'), name='unique_varglobalescostodatos'),
        ),
    ]
