# Generated by Django 5.2.4 on 2025-10-07 09:42

import apps.codificadores.models
import apps.flujo.models
import django.core.validators
import django.db.models.deletion
import django.db.models.functions.datetime
import django.utils.timezone
import django_choices_field.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('codificadores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fecha', models.DateField(verbose_name='Date')),
                ('fecha_creacion', models.DateTimeField(db_default=django.db.models.functions.datetime.Now(), verbose_name='Create at')),
                ('numerocontrol', models.CharField(max_length=50, verbose_name='Control Number')),
                ('numeroconsecutivo', models.IntegerField(verbose_name='Consecutive Number')),
                ('suma_importe', models.DecimalField(decimal_places=2, default=0.0, max_digits=18, verbose_name='Amount')),
                ('observaciones', models.TextField(blank=True, null=True, verbose_name='Observations')),
                ('estado', django_choices_field.fields.IntegerChoicesField(choices=[(1, 'Edición'), (2, 'Confirmado'), (3, 'Rechazado'), (4, 'Cancelado'), (5, 'Con Errores')], choices_enum=apps.flujo.models.EstadosDocumentos, db_comment='Estado del documento 1:Edición, 2:Confirmado, 3:Rechazado', default=1, verbose_name='Status')),
                ('reproceso', models.BooleanField(default=False, verbose_name='Reprocessing')),
                ('editar_nc', models.BooleanField(default=False)),
                ('comprob', models.CharField(blank=True, max_length=150, null=True)),
                ('anno', models.IntegerField(default=0)),
                ('mes', models.IntegerField(default=0)),
                ('confconsec', django_choices_field.fields.IntegerChoicesField(choices=[(1, 'Por departamento'), (2, 'Unico en el sistema')], choices_enum=apps.codificadores.models.ConfigNumero, db_comment='Para guardar el tipo de conf para el consecutivo y poder establecer la constarint', default=1)),
                ('confcontrol', django_choices_field.fields.IntegerChoicesField(choices=[(1, 'Por departamento'), (2, 'Unico en el sistema')], choices_enum=apps.codificadores.models.ConfigNumero, db_comment='Para guardar el tipo de conf para el numero de control y poder establecer la constarint', default=1)),
                ('error', models.BooleanField(default=False, verbose_name='Error')),
                ('cerrado', models.BooleanField(default=False)),
                ('departamento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documento_departamento', to='codificadores.departamento')),
                ('tipodocumento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documento_tipodocumento', to='codificadores.tipodocumento', verbose_name='Tipo Documento')),
                ('ueb', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documento_ueb', to='codificadores.unidadcontable')),
            ],
            options={
                'db_table': 'fp_documento',
                'ordering': ['ueb', 'departamento', '-numeroconsecutivo', 'tipodocumento'],
            },
        ),
        migrations.CreateModel(
            name='DocumentoAjuste',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('documento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentoajuste_documento', to='flujo.documento')),
                ('motivoajuste', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documentoajuste_motivo', to='codificadores.motivoajuste', verbose_name='Adjustment Reason')),
            ],
            options={
                'db_table': 'fp_documentoajuste',
            },
        ),
        migrations.CreateModel(
            name='DocumentoDetalle',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cantidad', models.DecimalField(decimal_places=6, default=0.0, max_digits=18, validators=[django.core.validators.MinValueValidator(0.0001, message='El valor debe ser >= 0')], verbose_name='Quantity')),
                ('precio', models.DecimalField(decimal_places=7, default=0.0, max_digits=18, verbose_name='Price')),
                ('importe', models.DecimalField(decimal_places=2, default=0.0, max_digits=18, verbose_name='Amount')),
                ('existencia', models.DecimalField(decimal_places=6, default=0.0, max_digits=18, verbose_name='Existence')),
                ('estado', django_choices_field.fields.IntegerChoicesField(choices=[(1, 'Bueno'), (2, 'Deficiente'), (3, 'Rechazo')], choices_enum=apps.codificadores.models.EstadoProducto, verbose_name='Status')),
                ('error', models.BooleanField(default=False, verbose_name='Error')),
                ('operacion', models.SmallIntegerField(choices=[(1, 'Entrada'), (-1, 'Salida')], default=1)),
                ('documento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentodetalle_documento', to='flujo.documento')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documentodetalle_producto', to='codificadores.productoflujo', verbose_name='Product')),
            ],
            options={
                'db_table': 'fp_documentodetalle',
            },
        ),
        migrations.CreateModel(
            name='DocumentoDetalleEstado',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('existencia', models.DecimalField(decimal_places=6, default=0.0, max_digits=18, verbose_name='Existence')),
                ('estado', django_choices_field.fields.IntegerChoicesField(choices=[(1, 'Bueno'), (2, 'Deficiente'), (3, 'Rechazo')], choices_enum=apps.codificadores.models.EstadoProducto, verbose_name='Status')),
                ('precio', models.DecimalField(decimal_places=7, default=0.0, max_digits=18, verbose_name='Price')),
                ('cantidad', models.DecimalField(decimal_places=6, default=0.0, max_digits=18, verbose_name='Quantity')),
                ('importe', models.DecimalField(decimal_places=2, default=0.0, max_digits=18, verbose_name='Amount')),
                ('operacion', models.SmallIntegerField(choices=[(1, 'Entrada'), (-1, 'Salida')], default=1)),
                ('error', models.BooleanField(default=False, verbose_name='Error')),
                ('documentodetalle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentodetalleestado_detalle', to='flujo.documentodetalle')),
                ('producto', models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='documentodetalleproducto_estado', to='codificadores.productoflujo', verbose_name='Product')),
            ],
            options={
                'db_table': 'fp_documentodetalleestado',
            },
        ),
        migrations.CreateModel(
            name='DocumentoDetalleProducto',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('existencia', models.DecimalField(decimal_places=6, default=0.0, max_digits=18, verbose_name='Existence')),
                ('estado', django_choices_field.fields.IntegerChoicesField(choices=[(1, 'Bueno'), (2, 'Deficiente'), (3, 'Rechazo')], choices_enum=apps.codificadores.models.EstadoProducto, default=1, verbose_name='Status')),
                ('precio', models.DecimalField(decimal_places=7, default=0.0, max_digits=18, verbose_name='Price')),
                ('cantidad', models.DecimalField(decimal_places=6, default=0.0, max_digits=18, verbose_name='Quantity')),
                ('importe', models.DecimalField(decimal_places=2, default=0.0, max_digits=18, verbose_name='Amount')),
                ('operacion', models.SmallIntegerField(choices=[(1, 'Entrada'), (-1, 'Salida')], default=1)),
                ('error', models.BooleanField(default=False, verbose_name='Error')),
                ('documentodetalle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentodetalleproducto_detalle', to='flujo.documentodetalle')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documentodetalleproducto_producto', to='codificadores.productoflujo', verbose_name='Product')),
            ],
            options={
                'db_table': 'fp_documentodetalleproducto',
            },
        ),
        migrations.CreateModel(
            name='DocumentoDetalleProductoNC',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('existencia', models.DecimalField(decimal_places=6, default=0.0, max_digits=18, verbose_name='Existence')),
                ('estado', django_choices_field.fields.IntegerChoicesField(choices=[(1, 'Bueno'), (2, 'Deficiente'), (3, 'Rechazo')], choices_enum=apps.codificadores.models.EstadoProducto, default=1, verbose_name='Status')),
                ('precio', models.DecimalField(decimal_places=7, default=0.0, max_digits=18, verbose_name='Price')),
                ('cantidad', models.DecimalField(decimal_places=6, default=0.0, max_digits=18, verbose_name='Quantity')),
                ('importe', models.DecimalField(decimal_places=2, default=0.0, max_digits=18, verbose_name='Amount')),
                ('operacion', models.SmallIntegerField(choices=[(1, 'Entrada'), (-1, 'Salida')], default=-1)),
                ('error', models.BooleanField(default=False, verbose_name='Error')),
                ('documentodetalle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentodetalleproductonc_detalle', to='flujo.documentodetalle')),
                ('normaconsumodetalles', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentodetalleproductoncdetalle_detalle', to='codificadores.normaconsumodetalle')),
            ],
            options={
                'db_table': 'fp_documentodetalleproductonc',
                'ordering': ['normaconsumodetalles__producto__descripcion'],
            },
        ),
        migrations.CreateModel(
            name='DocumentoDetalleReproceso',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('existencia', models.DecimalField(decimal_places=6, default=0.0, max_digits=18, verbose_name='Existence')),
                ('estado', django_choices_field.fields.IntegerChoicesField(choices=[(1, 'Bueno'), (2, 'Deficiente'), (3, 'Rechazo')], choices_enum=apps.codificadores.models.EstadoProducto, default=1, verbose_name='Status')),
                ('precio', models.DecimalField(decimal_places=7, default=0.0, max_digits=18, verbose_name='Price')),
                ('cantidad', models.DecimalField(decimal_places=6, default=0.0, max_digits=18, validators=[django.core.validators.MinValueValidator(0.0001, message='El valor debe ser >= 0')], verbose_name='Quantity')),
                ('importe', models.DecimalField(decimal_places=2, default=0.0, max_digits=18, verbose_name='Amount')),
                ('operacion', models.SmallIntegerField(choices=[(1, 'Entrada'), (-1, 'Salida')], default=-1)),
                ('error', models.BooleanField(default=False, verbose_name='Error')),
                ('documentodetalle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentodetallereprocesodeficiente_documentodetalle', to='flujo.documentodetalle')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documentodetallereproceso_producto', to='codificadores.productoflujo')),
            ],
            options={
                'db_table': 'fp_documentodetallereproceso',
            },
        ),
        migrations.CreateModel(
            name='DocumentoDetalleReprocesoDeficiente',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('existencia', models.DecimalField(decimal_places=6, default=0.0, max_digits=18, verbose_name='Existence')),
                ('estado', django_choices_field.fields.IntegerChoicesField(choices=[(1, 'Bueno'), (2, 'Deficiente'), (3, 'Rechazo')], choices_enum=apps.codificadores.models.EstadoProducto, default=2, verbose_name='Status')),
                ('precio', models.DecimalField(decimal_places=7, default=0.0, max_digits=18, validators=[django.core.validators.MinValueValidator(1e-07, message='El valor debe ser >= 0')], verbose_name='Price')),
                ('cantidad', models.DecimalField(decimal_places=6, default=0.0, max_digits=18, validators=[django.core.validators.MinValueValidator(0.0001, message='El valor debe ser >= 0')], verbose_name='Quantity')),
                ('importe', models.DecimalField(decimal_places=2, default=0.0, max_digits=18, verbose_name='Amount')),
                ('operacion', models.SmallIntegerField(choices=[(1, 'Entrada'), (-1, 'Salida')], default=-1)),
                ('error', models.BooleanField(default=False, verbose_name='Error')),
                ('documentodetalle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentodetallereprocesodeficiente_reproceso', to='flujo.documentodetalle')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documentodetallereprocesodeficiente_detalle', to='codificadores.productoflujo')),
            ],
            options={
                'db_table': 'fp_documentodetallereprocesodeficientes',
            },
        ),
        migrations.CreateModel(
            name='DocumentoDetalleTransfDptoControlTecnico',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cantidad', models.DecimalField(decimal_places=6, default=0.0, max_digits=18, verbose_name='Quantity')),
                ('precio', models.DecimalField(decimal_places=7, default=0.0, max_digits=18, verbose_name='Price')),
                ('importe', models.DecimalField(decimal_places=2, default=0.0, max_digits=18, verbose_name='Amount')),
                ('existencia', models.DecimalField(decimal_places=6, default=0.0, max_digits=18, verbose_name='Existence')),
                ('buenos', models.IntegerField(default=0, verbose_name='Good')),
                ('defectuoso_cc', models.IntegerField(default=0, verbose_name='Defective CC')),
                ('defectuoso_cien', models.IntegerField(default=0, verbose_name='Defective 100%')),
                ('sensorial', models.IntegerField(default=0, verbose_name='Sensory Test')),
                ('rotos', models.IntegerField(default=0, verbose_name='Broken')),
                ('operacion', models.SmallIntegerField(choices=[(1, 'Entrada'), (-1, 'Salida')], default=1)),
                ('documento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentodetalletransfdptocontroltecnico_documento', to='flujo.documento')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documentodetalletransfdptocontroltecnico_producto', to='codificadores.productoflujo', verbose_name='Product')),
            ],
            options={
                'db_table': 'fp_documentodetalletransfdptocontroltecnico',
            },
        ),
        migrations.CreateModel(
            name='DocumentoDetalleVenta',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('importe', models.DecimalField(decimal_places=2, default=0.0, max_digits=18, verbose_name='Amount')),
                ('documentodetalle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documentodetalleventa_detalle', to='flujo.documentodetalle')),
            ],
            options={
                'db_table': 'fp_documentodetalleventa',
            },
        ),
        migrations.CreateModel(
            name='DocumentoDevolucion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('documento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documentodevolucion_documento', to='flujo.documento')),
            ],
            options={
                'db_table': 'fp_documentodevolucion',
            },
        ),
        migrations.CreateModel(
            name='DocumentoDevolucionRecibida',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('documento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documentodevolucionrecibida_documento', to='flujo.documento')),
                ('documentoorigen', models.ForeignKey(db_comment='Documento que originó la devolucion hacia el departamento', on_delete=django.db.models.deletion.PROTECT, related_name='documentodevolucionrecibida_documentoorigen', to='flujo.documento')),
            ],
            options={
                'db_table': 'fp_documentodevolucionrecibida',
            },
        ),
        migrations.CreateModel(
            name='DocumentoOrigenVersat',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('documentoversat', models.IntegerField()),
                ('fecha_documentoversat', models.DateTimeField(db_default=django.db.models.functions.datetime.Now(), verbose_name='Fecha versat at')),
                ('documento_origen', models.JSONField(blank=True, default=dict, null=True)),
                ('documento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentoorigenversat_documento', to='flujo.documento')),
            ],
            options={
                'db_table': 'fp_documentoorigenversat',
            },
        ),
        migrations.CreateModel(
            name='DocumentoTransfDepartamento',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('departamento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documentotransfdepartamento_departamento', to='codificadores.departamento', verbose_name='Department')),
                ('documento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentotransfdepartamento_documento', to='flujo.documento')),
            ],
            options={
                'db_table': 'fp_documentotransfdepartamento',
            },
        ),
        migrations.CreateModel(
            name='DocumentoTransfDepartamentoRecibida',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('documento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documentotransfdepartamentorecibida_documento', to='flujo.documento')),
                ('documentoorigen', models.ForeignKey(db_comment='Documento que originó la transferencia hacia el departamento', on_delete=django.db.models.deletion.PROTECT, related_name='documentotransfdepartamentorecibida_documentoorigen', to='flujo.documento')),
            ],
            options={
                'db_table': 'fp_documentotransfdesdedepartamento',
            },
        ),
        migrations.CreateModel(
            name='DocumentoTransfExterna',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('documento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentotransfext_documento', to='flujo.documento')),
                ('unidadcontable', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documentotransfext_unidadcontable', to='codificadores.unidadcontable')),
            ],
            options={
                'db_table': 'fp_documentotransfexterna',
            },
        ),
        migrations.CreateModel(
            name='DocumentoTransfExternaDptoDestino',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('departamento_destino', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documentotransfext_departamento_destino', to='codificadores.departamento')),
                ('documentotransfext', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentotransfextdptodest_documento', to='flujo.documento')),
            ],
            options={
                'db_table': 'fp_documentotransfexternadptodestino',
            },
        ),
        migrations.CreateModel(
            name='DocumentoTransfExternaRecibida',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('documento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentotransfextrecibida_documento', to='flujo.documento')),
                ('unidadcontable', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documentotransfextrecibida_unidadcontable', to='codificadores.unidadcontable')),
            ],
            options={
                'db_table': 'fp_documentotransfexternarecibida',
            },
        ),
        migrations.CreateModel(
            name='DocumentoTransfExternaRecibidaDocOrigen',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('documento', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='documentotransfextrecibidadocorigen_documento', to='flujo.documento')),
                ('documentoorigen', models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='documentotransfextrecibida_documentoorigen', to='flujo.documento')),
            ],
            options={
                'db_table': 'fp_documentotransfexternarecibidadocorigen',
            },
        ),
        migrations.CreateModel(
            name='DocumentoVersatRechazado',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('documentoversat', models.IntegerField()),
                ('fecha_documentoversat', models.DateField()),
                ('fecha_rechazo', models.DateTimeField(db_default=django.db.models.functions.datetime.Now())),
                ('documento_origen', models.JSONField(blank=True, default=dict, null=True)),
                ('ueb', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documentoversatrechazado_ueb', to='codificadores.unidadcontable')),
            ],
            options={
                'db_table': 'fp_documentoversatrechazado',
            },
        ),
        migrations.CreateModel(
            name='ExistenciaDpto',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('estado', django_choices_field.fields.IntegerChoicesField(choices=[(1, 'Bueno'), (2, 'Deficiente'), (3, 'Rechazo')], choices_enum=apps.codificadores.models.EstadoProducto, verbose_name='Status')),
                ('cantidad_inicial', models.DecimalField(decimal_places=6, default=0.0, max_digits=18, verbose_name='Cantidad Inicial')),
                ('cantidad_entrada', models.DecimalField(decimal_places=6, default=0.0, max_digits=18, verbose_name='Entradas')),
                ('cantidad_salida', models.DecimalField(decimal_places=6, default=0.0, max_digits=18, verbose_name='Salidas')),
                ('cantidad_final', models.DecimalField(decimal_places=6, default=0.0, max_digits=18, verbose_name='Cantidad Final')),
                ('precio', models.DecimalField(decimal_places=7, default=0.0, max_digits=18, verbose_name='Price')),
                ('importe', models.DecimalField(decimal_places=2, default=0.0, max_digits=18, verbose_name='Amount')),
                ('anno', models.IntegerField(default=0)),
                ('mes', models.IntegerField(default=0)),
                ('departamento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='existencias_departamento', to='codificadores.departamento')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='existencias_producto', to='codificadores.productoflujo', verbose_name='Product')),
                ('ueb', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='existencias_ueb', to='codificadores.unidadcontable')),
            ],
            options={
                'db_table': 'fp_existenciadpto',
            },
        ),
        migrations.CreateModel(
            name='FechaCierreMes',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fecha', models.DateField(verbose_name='Date')),
                ('ueb', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fechacierremes_ueb', to='codificadores.unidadcontable', verbose_name='UEB')),
            ],
            options={
                'db_table': 'fp_fechacierremes',
            },
        ),
        migrations.CreateModel(
            name='FechaPeriodo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fecha', models.DateField(verbose_name='Date')),
                ('departamento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fechaperiodo_departamento', to='codificadores.departamento', verbose_name='Department')),
                ('ueb', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fechaperiodo_ueb', to='codificadores.unidadcontable', verbose_name='UEB')),
            ],
            options={
                'db_table': 'fp_fechaperiodo',
            },
        ),
        migrations.CreateModel(
            name='NormaOperativa',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('ueb', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='normaoperativa_ueb', to='codificadores.unidadcontable', verbose_name='UEB')),
            ],
            options={
                'verbose_name': 'Norma Operativa',
                'verbose_name_plural': 'Normas Operativas',
                'db_table': 'fp_normaoperativa',
            },
        ),
        migrations.CreateModel(
            name='NormaOperativaDetalle',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('norma', models.DecimalField(decimal_places=6, default=0.0, max_digits=18)),
                ('medida', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='medida_normaoperativadetalle', to='codificadores.medida', verbose_name='Medida')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='productonormaoperativa_detalle', to='codificadores.productoflujo')),
            ],
            options={
                'db_table': 'fp_normaoperativa_detalle',
            },
        ),
        migrations.CreateModel(
            name='DocumentoDetalleProductoNO',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('existencia', models.DecimalField(decimal_places=6, default=0.0, max_digits=18, verbose_name='Existence')),
                ('estado', django_choices_field.fields.IntegerChoicesField(choices=[(1, 'Bueno'), (2, 'Deficiente'), (3, 'Rechazo')], choices_enum=apps.codificadores.models.EstadoProducto, default=1, verbose_name='Status')),
                ('precio', models.DecimalField(decimal_places=7, default=0.0, max_digits=18, verbose_name='Price')),
                ('cantidad', models.DecimalField(db_comment='Cantidad de productos producidos usando esta Norma Operativa', decimal_places=6, default=0.0, max_digits=18, verbose_name='Quantity')),
                ('cantidad_usada', models.DecimalField(db_comment='Cantidad que se usó del producto de la norma operativa', decimal_places=6, default=0.0, max_digits=18, verbose_name='Quantity')),
                ('importe', models.DecimalField(decimal_places=2, default=0.0, max_digits=18, verbose_name='Amount')),
                ('operacion', models.SmallIntegerField(choices=[(1, 'Entrada'), (-1, 'Salida')], default=-1)),
                ('error', models.BooleanField(default=False, verbose_name='Error')),
                ('orden', models.IntegerField(default=0, verbose_name='Orden')),
                ('documentodetalle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentodetalleproductono_detalle', to='flujo.documentodetalle')),
                ('normaoperativadetalle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documentodetalleproductono_no', to='flujo.normaoperativadetalle')),
            ],
            options={
                'db_table': 'fp_documentodetalleproductono',
                'ordering': ['documentodetalle', 'orden'],
            },
        ),
        migrations.CreateModel(
            name='NormaOperativaProducto',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cantidad', models.DecimalField(decimal_places=6, default=0.0, max_digits=18)),
                ('fecha_creacion', models.DateTimeField(default=django.utils.timezone.now)),
                ('idsispax', models.CharField(blank=True, max_length=40, null=True)),
                ('medida', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='medida_normaoperativaproducto', to='codificadores.medida', verbose_name='Medida')),
                ('normaoperativa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='normaoperativaproductos', to='flujo.normaoperativa')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='productonormaoperativa', to='codificadores.productoflujo')),
            ],
            options={
                'db_table': 'fp_normaoperativa_producto',
                'ordering': ['producto__descripcion'],
            },
        ),
        migrations.AddField(
            model_name='normaoperativadetalle',
            name='normaoperativaproducto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='normaoperativaproducto_detalles', to='flujo.normaoperativaproducto'),
        ),
        migrations.CreateModel(
            name='NumeroDocumentos',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tiponumero', django_choices_field.fields.IntegerChoicesField(choices=[(1, 'Número Consecutivo'), (2, 'Número de Control')], choices_enum=apps.codificadores.models.TipoNumeroDoc, default=1, verbose_name='Tipo número')),
                ('numero', models.IntegerField(default=0, verbose_name='Número')),
                ('departamento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='numdoc_departamento', to='codificadores.departamento', verbose_name='Department')),
                ('ueb', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='numdoc_ueb', to='codificadores.unidadcontable', verbose_name='UEB')),
            ],
            options={
                'db_table': 'fp_numerodocumentos',
            },
        ),
        migrations.AddIndex(
            model_name='documento',
            index=models.Index(fields=['ueb', 'departamento', 'fecha', 'estado'], name='fp_document_ueb_id_f0de69_idx'),
        ),
        migrations.AddIndex(
            model_name='documento',
            index=models.Index(fields=['fecha', 'numeroconsecutivo'], name='fp_document_fecha_43c607_idx'),
        ),
        migrations.AddConstraint(
            model_name='documento',
            constraint=models.UniqueConstraint(condition=models.Q(('confconsec', 1)), fields=('numeroconsecutivo', 'departamento', 'mes', 'anno', 'ueb'), name='unique_numeroconsecutivo_departamento_tipodocumento'),
        ),
        migrations.AddConstraint(
            model_name='documento',
            constraint=models.UniqueConstraint(condition=models.Q(('confconsec', 2)), fields=('numeroconsecutivo', 'mes', 'anno', 'ueb'), name='unique_numeroconsecutivo_ueb'),
        ),
        migrations.AddConstraint(
            model_name='documento',
            constraint=models.UniqueConstraint(condition=models.Q(('confcontrol', 1)), fields=('numerocontrol', 'departamento', 'anno', 'ueb'), name='unique_numerocontrol_departamento'),
        ),
        migrations.AddConstraint(
            model_name='documento',
            constraint=models.UniqueConstraint(condition=models.Q(('confcontrol', 2)), fields=('numerocontrol', 'anno', 'ueb'), name='unique_numerocontrol_ueb'),
        ),
        migrations.AddIndex(
            model_name='documentodetalle',
            index=models.Index(fields=['documento'], name='fp_document_documen_8a66cb_idx'),
        ),
        migrations.AddIndex(
            model_name='documentodetalle',
            index=models.Index(fields=['producto'], name='fp_document_product_51ae72_idx'),
        ),
        migrations.AddConstraint(
            model_name='documentodetalle',
            constraint=models.UniqueConstraint(fields=('documento', 'estado', 'producto'), name='unique_documentodetalle_documento_estado_producto'),
        ),
        migrations.AddIndex(
            model_name='existenciadpto',
            index=models.Index(fields=['producto', 'estado', 'departamento', 'ueb', 'mes', 'anno'], name='fp_existenc_product_590d27_idx'),
        ),
        migrations.AddConstraint(
            model_name='existenciadpto',
            constraint=models.UniqueConstraint(fields=('producto', 'estado', 'departamento', 'ueb', 'mes', 'anno'), name='unique_existencias_producto_estado_departamento_ueb_mes_anno'),
        ),
        migrations.AddConstraint(
            model_name='fechacierremes',
            constraint=models.UniqueConstraint(fields=('fecha', 'ueb'), name='unique_fechacierremes_fecha_ueb'),
        ),
        migrations.AddConstraint(
            model_name='fechaperiodo',
            constraint=models.UniqueConstraint(fields=('fecha', 'departamento', 'ueb'), name='unique_fechaperiodo_fecha_departamento_ueb'),
        ),
        migrations.AddIndex(
            model_name='normaoperativa',
            index=models.Index(fields=['fecha', 'ueb'], name='fp_normaope_fecha_af38e9_idx'),
        ),
        migrations.AddConstraint(
            model_name='normaoperativa',
            constraint=models.UniqueConstraint(fields=('fecha', 'ueb'), name='unique_normaoperativa_fecha_ueb'),
        ),
        migrations.AddIndex(
            model_name='numerodocumentos',
            index=models.Index(fields=['departamento', 'ueb'], name='fp_numerodo_departa_6f3c32_idx'),
        ),
        migrations.AddIndex(
            model_name='numerodocumentos',
            index=models.Index(fields=['ueb'], name='fp_numerodo_ueb_id_be9977_idx'),
        ),
        migrations.AddConstraint(
            model_name='numerodocumentos',
            constraint=models.UniqueConstraint(fields=('tiponumero', 'departamento', 'ueb'), name='unique_numdocumentos_tiponumero_departamento_ueb'),
        ),
    ]
